.PHONY: install test test-cov lint format build dev

install:
	npm install

test:
	npm run test:run

test-cov:
	npm run test:coverage

lint:
	npm run lint

format:
	npm run lint -- --fix

build:
	npm run build

dev:
	npm run dev
