version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: quizling-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-quizling}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - quizling-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  quizling-network:
    driver: bridge
