name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    env:
      AZURE_OPENAI_ENDPOINT: "https://example.com"
      AZURE_OPENAI_KEY: this-is-not-a-key
      AZURE_OPENAI_VERSION: 2024-02-15-preview
      AZURE_OPENAI_DEPLOYMENT: gpt-5-mini
      MONGO_DATABASE: quizling
      MONGODB_URI: mongodb://admin:password@localhost:27017/quizling?authSource=admin
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest

